// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'Moonlight Example',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/okzyrox/moonlight' }],
			// The sidebar is fully autogenerated from the loaded extractor output
            // Although can still be customised for other sections like guides or something
			sidebar: [
				{
					label: 'API Reference',
					items: [{ autogenerate: { directory: 'api' } }],
				},
			],
		}),
	],
});
